// let words = ['BANJO','KITTEN','HORSE','CARROT','COMPUTER', 'POTATO', 'JAVASCRIPT', 'ASSEMBLY', 'CHIEF', 'BRACELET', 'CAMPAIGN', 'RUSSIA', 'CAMBODIA', 'CAUTION', 'CONSULTANT']

let words = ['BANJO','KITTEN','HORSE','CARROT']
