let newGame = new GameLogic()
console.log(newGame.retrieveWord())
console.log(newGame.words)
console.log(newGame.retrieveWord())
console.log(newGame.words)
console.log(newGame.retrieveWord())
console.log(newGame.words)
console.log(newGame.retrieveWord())
console.log(newGame.words)
console.log(newGame.retrieveWord())
console.log(newGame.words)

console.log(newGame.retrieveWord())
console.log(newGame.words)
